### ISSUE TITLE
I'm too scared to send strings

### ISSUE THREAD

**Issue by ConfusedVorlon** [onesky/plugin-xcode#10]
what are all these NULL/NULL files?

![2015-01-19 03 43 19 pm](https://cloud.githubusercontent.com/assets/586910/5802967/ff04b0ec-9ff1-11e4-8eb4-98d96cad60f8.png)

**Comment by bretdabaker** [comment]
Are these files contained in the localizable folders? e.g. en.lproj? The plugin works by detecting the language of the .strings file by the name of the containing folder.

**Comment by ConfusedVorlon** [comment]
yes - they're all in the appropriate folders.
they are one folder down from my project root though (Localisation/fr.lproj)

this was before I nuked all my old stuff and accepted the plugin folder assumptions.

**Comment by bretdabaker** [comment]
String files that are not contained in [locale].lproj folder will now be ignored.

https://github.com/onesky/plugin-xcode/releases/tag/1.4.8

**Comment by ConfusedVorlon** [comment]
plugin is working perfectly for me now.
