### ISSUE TITLE
Updating string in Base storyboard/xib does not update .strings file

### ISSUE THREAD

**Issue by andresgarza** [onesky/plugin-xcode#14]
Steps to reproduce:

1. Create sample Xcode project with Base Internationalization enabled (it's the default Xcode >5)
2. Make sure at least one storyboard/xib has localizable strings
3. Configure the `Project Properties` from the OneSky menu (to an empty project in OneSky) 
3. `Generate/Update Strings Files...` from the OneSky menu.
4. Notice the corresponding `.strings` files that are correctly generated for each storyboard/xib
5. Change any string directly in a storyboard/xib
6. `Generate/Update Strings Files...` from the OneSky menu.
7. Notice how the corresponding `.strings` file is **not** updated.

**Comment by bretdabaker** [comment]
Fixed with commit bfa8458

**Comment by andresgarza** [comment]
Verified that it works great for xib/nib files, but not for storyboard files :(

**Comment by bretdabaker** [comment]
I just tested with storyboard files again and they are working as expected, can you please give me more information on your problem?

**Comment by bretdabaker** [comment]
I am closing this issue for now, if you can provide more info or the storyboard, please reopen the issue.
