### ISSUE TITLE
Support for localized JSON files

### ISSUE THREAD

**Issue by andresgarza** [onesky/plugin-xcode#15]
It is becoming very common to have JSON files within Xcode projects. Would be great if the plugin could automatically send/sync these types of files.

**Comment by bretdabaker** [comment]
Added support for `.plist` and `.json` files in [1.8.0](https://github.com/onesky/plugin-xcode/releases/tag/1.8.0)!

**Comment by andresgarza** [comment]
@bretdabaker this is great. thanks!
