### ISSUE TITLE
Support XCode 6.3

### ISSUE THREAD

**Issue by IAmMalte** [onesky/plugin-xcode#16]
For me, the Plugin does not work with xcode 6.3. The menu item does not show up.

**Comment by bretdabaker** [comment]
Fixed in 2f9c2a10bb1f97fffab9166ea7e3b24bebaf78d7

**Comment by linktoming** [comment]
It's still not working for Xcode 6.3.2 @bretdabaker

**Comment by bretdabaker** [comment]
Fixed: https://github.com/onesky/plugin-xcode/releases/tag/1.5.3

We have to update the info.plist every time there's new Xcode release.
