### ISSUE TITLE
NSLocalizedString variants unsupported 

### ISSUE THREAD

**Issue by tomco** [onesky/plugin-xcode#18]
First of all thank you for this plugin. It is super nice!

But it seems that only the very basic `NSLocalizedString` is supported.

Have a look a the definition of `NSLocalizedString`:

```swift
/// Returns a localized string, using the main bundle if one is not specified.
@warn_unused_result
public func NSLocalizedString(key: String, tableName: String? = default, bundle: NSBundle = default, value: String = default, comment: String) -> String
```

There are many possible calls with different number of arguments to `NSLocalizedString` since many of the arguments are defined with default values.

So I ran a little test using the **Generate/Update Strings Files...** function of this plugin. Only the first variant works:

```swift
NSLocalizedString("1", comment: "WORKS")

NSLocalizedString("2", tableName: "someTable", comment: "NOTHING")
NSLocalizedString("3", tableName: "someTable", bundle: bundle, value: "bla", comment: "DOES NOT WORK")
NSLocalizedString("4", bundle: bundle, comment: "THIS DOES NOTHING")
NSLocalizedString("5", bundle: bundle, value: "lalala", comment: "ALSO NOT WORKING")
NSLocalizedString("6", tableName: nil, bundle: bundle, value: "blub", comment: "THIS IS BROKEN")
```

I'm especially interested in using `tableName` to separate keys into multiple string files and using the `value` argument to supply a default (base) translation.

Hope you can add support for this soon.

**Comment by bretdabaker** [comment]
The feature relies on `genstrings` command tool to generate strings from source and ib files, and it is a known bug for genstrings not working properly with .swift files in Xcode 6.4 and 7.

https://openradar.appspot.com/22133811
