### ISSUE TITLE
Can't generate string files in Xcode when OSLocalizedString is used

### ISSUE THREAD

**Issue by Tibbs** [onesky/plugin-xcode#19]
I replaced all NSLocalizedStrings with OSLocalizedString.
I tried to generate and upload string files using the Xcode plugin, but it did not find OSLocalizedString localizations at all.

The plugin should be compatible with plugin-ios-ota, which would make both tools really great.

**Comment by bretdabaker** [comment]
Fixed in https://github.com/onesky/plugin-xcode/releases/tag/1.6.1
