### ISSUE TITLE
Incorrect language codes

### ISSUE THREAD

**Issue by samuelbradshaw** [onesky/plugin-xcode#21]
Some translations download with the incorrect language code – for example:
– Portuguese downloads as pt-BR
– Spanish downloads as es-419

**Comment by bretdabaker** [comment]
The plugin uses the codes of the selected languages of your OneSky project. What does the **Manage Languages** page of your project look like?

![screen shot 2016-01-12 at 11 12 30 am](https://cloud.githubusercontent.com/assets/990341/12253874/2365816e-b91e-11e5-92e1-a474ba7e9a93.png)

**Comment by samuelbradshaw** [comment]
I have generic Spanish and Portuguese selected:

<img width="1226" alt="screenshot_39" src="https://cloud.githubusercontent.com/assets/7323052/12254115/9312ecda-b8a2-11e5-9508-ccd8cc781233.png">

**Comment by bretdabaker** [comment]
Does the download translations dialog show the incorrect codes next to the filenames as well?

![screen shot 2016-01-12 at 11 53 22 am](https://cloud.githubusercontent.com/assets/990341/12254432/37eb82a0-b923-11e5-8522-1e45fc2d74ec.png)

**Comment by samuelbradshaw** [comment]
It shows es-419 and pt-BR for some reason – so it may be a problem at OneSky. Any idea what's going on?:

<img width="1421" alt="screenshot_41" src="https://cloud.githubusercontent.com/assets/7323052/12254468/05a694c4-b8a6-11e5-8b30-394cff1fc574.png">

**Comment by bretdabaker** [comment]
Let me check with them quickly. Thanks for the information!

**Comment by samuelbradshaw** [comment]
Thank you! For now I've been just renaming the files after they download.

**Comment by bretdabaker** [comment]
Our backend developer spotted a legacy language configuration in your project, he has cleared the settings now, please try and see if it's working.

I am closing the issue now as it's not related to the plugin, feel free to shoot me an email if you have any problem.

Thanks!

**Comment by samuelbradshaw** [comment]
Thank you!
