### ISSUE TITLE
The request timed out when uploading all files to OneSky

### ISSUE THREAD

**Issue by SjoerdPerfors** [onesky/plugin-xcode#22]
Where can I found more about this issue? If I send each file one by one it goes ok.

**Comment by bretdabaker** [comment]
The plugin uploads the `.strings` files one at a time in a queue using `NSURLSession`, it could be that one of the files are too big in size and caused time-out or the server was unavailable temporarily.

Can you reproduce the problem? What is the size in kb of the largest file?

**Comment by SjoerdPerfors** [comment]
I can reproduce it each time. If I split it in 3 even batches it goes OK. 

Largest file is 94kb

<img width="571" alt="screen shot 2016-01-12 at 08 05 59" src="https://cloud.githubusercontent.com/assets/2300361/12257065/5cc2269e-b903-11e5-8793-d2279cfe7928.png">

**Comment by SjoerdPerfors** [comment]
Batch 72: NOK

Batch 62: OK
Batch 51: OK

Looks like the loader screen goes to 100% then I get about 20 errors, first that it's cancelled and then it's a timeout and this goes about 20 times.

**Comment by bretdabaker** [comment]
Please let me have your OneSky account email so that I can investigate from server side.

Thanks!

**Comment by SjoerdPerfors** [comment]
In your mail!

**Comment by bretdabaker** [comment]
Fixed in [1.6.4](https://github.com/onesky/plugin-xcode/releases/tag/1.6.4)

Thanks for helping!
