### ISSUE TITLE
No option to keep original language strings from uploading

### ISSUE THREAD

**Issue by samuelbradshaw** [onesky/plugin-xcode#23]
I just uploaded some string files in several languages for a project, and all of the English strings that were in the other languages' string files as placeholders uploaded as if they were translations. I don't think it did this before. Is there a way to revert or remove strings where the "translation" – placeholder – is the same as the original English?

**Comment by samuelbradshaw** [comment]
OneSky says they are able to revert the strings for me, but it would be nice to have a checkbox to not upload any strings that match the English strings as translations.

**Comment by bretdabaker** [comment]
The feature you requested is already handled from the server side. The default behaviour is to treat uploaded translations that match source as not translated.

We cannot reproduce the problem you have mentioned, if the problem persists it would be great if you can provide a separate demo project that can reproduce the problem. 

Thanks for your time.
