### ISSUE TITLE
Xcode 7.1 issue - Project list error

### ISSUE THREAD

**Issue by dongmai** [onesky/plugin-xcode#24]
Hi , I'm facing the issue when trying to use this plugin, I've put Api Key & Api Secret and the warning icon appeared  . Can anyone help me to resolve this ? Thanks.

<img width="453" alt="screen shot 2016-02-02 at 10 21 09 am" src="https://cloud.githubusercontent.com/assets/3855966/12738842/fd21297a-c996-11e5-9ff0-4a69882c2909.png">

**Comment by bretdabaker** [comment]
It could be that there are spaces in the API Key/Secret fields.

**Comment by dongmai** [comment]
Oh, that's it, Thank you.
