### ISSUE TITLE
Locale mismatch

### ISSUE THREAD

**Issue by stephenkopylov** [onesky/plugin-xcode#26]
Hi!
I just changed Hindi locale from "hi-IN" to "hi" in onesky, but in plugin's download dialog it still shows like "hi-IN"
Can you sync it? 

![screen shot 2016-02-13 at 15 23 37](https://cloud.githubusercontent.com/assets/5202281/13027803/00752932-d266-11e5-8f64-34d5db49974a.png)

![screen shot 2016-02-13 at 15 23 49](https://cloud.githubusercontent.com/assets/5202281/13027811/3be91258-d266-11e5-8e10-ec8a814d6b81.png)

**Comment by bretdabaker** [comment]
It's an issue with the API, we have already informed our backend engineer to follow up.

**Comment by stephenkopylov** [comment]
Thanks!
We really need it, cause it's so annoying to rename strings folder every time

**Comment by stephenkopylov** [comment]
Any progress with this issue?

**Comment by bretdabaker** [comment]
Added custom locale support for Xcode plugin in [1.8.7](https://github.com/onesky/plugin-xcode/releases/tag/1.8.7)
