### ISSUE TITLE
Upload documents doesn't work the second time

### ISSUE THREAD

**Issue by luicm** [onesky/plugin-xcode#27]
Hi
I'm using the plunging and it works great when I upload the strings the first time. but if i generate/update strings files and try to upload again (deprecate strings checked) it does not update the files in the server. 
Any ideas why this could be happening?
Thanks!

**Comment by luicm** [comment]
Hi,
Thank you for the quick fix. I have update the plugin and now it is uploading new sentence but the deprecation does not work. do you need me to send screen shots or video of the process? 
It also fail when i upload the document directly on the web

**Comment by bretdabaker** [comment]
Please create a new ticket, screenshots would be helpful. Thanks!
