### ISSUE TITLE
Mis-identification of the base language

### ISSUE THREAD

**Issue by hotdang-ca** [onesky/plugin-xcode#28]
As far as I can tell, my project's base language is English. However, when I Generate/Update Strings files, new strings are inserted into some other language (in this case, de-AT, though it has also and randomly selected pt).

My OneSky Project Properties does correctly have Base Language set to en, as well as having it specified in ~/Library/Application Support/OneSky/OneSkyProperties.plist

![screen shot 2016-04-06 at 10 52 38 am](https://cloud.githubusercontent.com/assets/7424855/14323357/d6d37756-fbe5-11e5-999b-1e2ef31ae2dd.png)

If I then upload Upload Files from this point, the one sky back-end does not receive these new strings (likely because they weren't in the base language), and i forget where in OneSky, but there is a warning/error issued regarding the string in de-AT, but not in the base language.

BUT... if I move those new strings inserted into de-AT, and move them to en, and then Upload Strings, this works correctly, and I see the new strings ready for translation on OneSky.

If i were to fathom a guess... $objects is an array, for which index 8 has the base language, as opposed to a dictionary specifying that value. I presume this is an open-source plugin, and I can try to fix by submitting a pull request?

**Comment by bretdabaker** [comment]
Hi, sorry the project is not open-source at the moment. 

The OneSkyProperties.plist is actually the `NSKeyedArchiver` cache of project settings objects `OSProject`, the array is managed by the archiver/unarchiver, so it's not related to the problem.

Does it happen every time you `Generate/Update Strings Files` or it only happens the first time? Can you create a simple project that can reproduce the problem?

Thanks for your time!

**Comment by hotdang-ca** [comment]
Hi, I've got it re-doing it, though I'm not sure the [Sample Project](https://github.com/hotdang-ca/helloonesky) file itself will help you diagnose.

In this case, it dumps the new strings into the filipino language.

**Comment by bretdabaker** [comment]
Thanks, will try out the sample projects soon.

**Comment by bretdabaker** [comment]
Fixed in [1.8.6](https://github.com/onesky/plugin-xcode/releases/tag/1.8.6)
