### ISSUE TITLE
generate/update string files should remember selection

### ISSUE THREAD

**Issue by ConfusedVorlon** [onesky/plugin-xcode#8]
I don't want my xibs localized, and I don't want my pod files localized.
I don't want to have to specify this every time I sync!

thanks.

**Comment by bretdabaker** [comment]
Again, I will work out a better file selection UI.

**Comment by bretdabaker** [comment]
We have improved the file selection UI so that ib files and source files are separated.
![generate_strings](https://cloud.githubusercontent.com/assets/990341/5912234/b5edadee-a60b-11e4-89f3-3f37432b4602.png)

https://github.com/onesky/plugin-xcode/releases/tag/1.4.8

**Comment by ConfusedVorlon** [comment]
that looks better - it isn't what I get from the link though...

the zip at the 1.4.8 link shows 1.4.6 in the info.plist

**Comment by bretdabaker** [comment]
I have fixed the release.

https://github.com/onesky/plugin-xcode/releases/download/1.4.8/OneSkyPlugin.zip

**Comment by ConfusedVorlon** [comment]
excellent - thank you.
