### ISSUE TITLE
please don't insist that string files have to be in the main project directory.

### ISSUE THREAD

**Issue by ConfusedVorlon** [onesky/plugin-xcode#9]
it's just really messy if you have to dump all your en.lproj, fr.lproj in the main directory.

much neater to move things into a subdirectory (I use Localisation)

**Comment by bretdabaker** [comment]
I am not sure where this comes from, would you be more specific? The plugin does support files in subdirectory, it searches for any .strings/.stringsdict files in the project. Take the following project structure as an example:

$SRCROOT/en.lproj/Localizable.strings
$SRCROOT/Resources/en.lproj/ViewController.strings

The plugin find both files for upload and sync without problems.

**Comment by ConfusedVorlon** [comment]
you're right - this all works splendidly now. Not sure why I got the wrong idea.

thanks.
